name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Setup and run pnpm install
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Run tests
        run: pnpm test
